apiVersion: apps/v1
kind: Deployment
metadata:
  name: manticore-dc2
  labels:
    env: production
    type: manticore-dc

spec:
  template:
     metadata:
       name: manticore-pod2
       labels:
         type: manticore
         feed: myfeedonk8s
         status: slave
     spec:
       affinity:
            nodeAffinity:
                 requiredDuringSchedulingIgnoredDuringExecution:
                   nodeSelectorTerms:
                        - matchExpressions:
                                - key: ip
                                  operator: In
                                  values:
                                    - qd2
       containers:
         - name: manticoresearch
           image: manticoresearch/manticore

           volumeMounts:
                 - name: manticore-data
                   mountPath: /var/lib/manticore
                 - name: manticore-config
                   mountPath: /etc/manticoresearch
                 - name: manticore-logs
                   mountPath: /var/log/manticore
           ports:
             - containerPort: 9306
             - containerPort: 9312
       volumes:
             - name: manticore-data
               hostPath:
                     path: /docker-data/manticore_data
                     type: Directory
             - name: manticore-config
               hostPath:
                     path: /docker-data/manticore_config
                     type: Directory
             - name: manticore-logs
               hostPath:
                     path: /docker-data/manticore_logs
                     type: Directory

  replicas: 1
  selector:
    matchLabels:
      type: manticore
      feed: myfeedonk8s
      status: slave
