## replace cluster_name  with cluster name with which you want to create cluster
- name: install Manticore and copy config
  hosts: 
    - node1-ip
    - node2-ip
  tasks:
    - name: install mysql client
      yum:
        state: present
        name:
          - mysql
    - name: create cluster folder
      file:
               path: "{{ item }}"
               state: directory
               owner: polkitd
      with_items:
            - /docker-data
            - /docker-data/manticore_data
            - /docker-data/manticore_config
            - /docker-data/manticore_logs
            - /docker-data/manticore_data/cluster_name
    - name: Copy manticore config file
      copy:
        src: new_files/manticore.conf
        dest: /docker-data/manticore_config
